language: erlang

otp_release:
  - 20.3

sudo: false
dist: trusty

#notifications:
#  email: false

#addons:
#  apt:
#    packages:
#    - fglrx
#    - opencl-headers

before_script:
  - set -e
  - git clone --depth 1 --branch cl-1.2.3 https://github.com/tonyrog/cl.git
  - export ERL_LIBS=`pwd`
  - export MAKEFLAGS=-j6

#
#  Fake a cl build since flgrx can not be installed in travis anymore, see
#  https://github.com/travis-ci/travis-ci/issues/5221
#  and thus cl can not be built but we need it below
#
script:
  - (cd cl/src && erlc +debug_info -o../ebin *erl && cp cl.app.src ../ebin/cl.app)
  - (mkdir cl/priv && touch cl/priv/cl.so )
  - make

after_success:
  - dialyzer --build_plt --apps erts kernel stdlib wx tools xmerl cl --statistics
  - dialyzer -n -Wno_improper_lists ebin/*.beam plugins/accel/*.beam plugins/autouv/*.beam plugins/commands/*.beam plugins/default/*.beam plugins/import_export/*.beam plugins/primitives/*.beam --statistics

# Needs a compiled cl-1.2.3
after_script:
  - make unix
